pipeline {
    agent any
    stages{
        
        stage("Build"){
            steps{
                dir("demoapi"){
                    sh "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 mvn -V clean install"
                }    
            }
        }
        stage("Test"){
            steps{
                dir("demoapi"){
                    sh "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 mvn test" 
               }
            }
        }

    }
}

